server:
  port: 8082

spring:
  devtools:
    restart:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test.db;AUTO_SERVER=TRUE
    username: testuser
    password: test1234

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /db

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  thymeleaf:
    suffix: .html
    cache: false
#    prefix: classpath:templates/default/